name: Run pre-commit
permissions:
  contents: read

on:
  push:
  pull_request:
    types: opened

jobs:
  pre-commit:
    uses: commit-check/.github/.github/workflows/pre-commit.yml@fcbd5e3e6cd0c675d58191af2c27ed25ff04a274 # main
