name: Run pre-commit
permissions:
  contents: read

on:
  push:
  pull_request:
    types: opened

jobs:
  pre-commit:
    uses: commit-check/.github/.github/workflows/pre-commit.yml@4a68c86b2edf1d31c5752bfeaf66b5425df8352e # main
